/**
 * Comprehensive mapping of ISO 3166-1 alpha-3 country codes to ISO 4217 currency codes
 * Based on World Bank country codes and their respective currencies
 */

export const countryCodeToCurrencyCode: Record<string, string> = {
  // Major currencies
  USA: 'USD',
  GBR: 'GBP',
  JPN: 'JPY',
  CAN: 'CAD',
  AUS: 'AUD',
  IND: 'INR',
  CHN: 'CNY',
  CHE: 'CHF', // Switzerland
  NOR: 'NOK',
  SWE: 'SEK',
  DNK: 'DKK',
  POL: 'PLN',
  TUR: 'TRY',
  RUS: 'RUB',
  BRA: 'BRL',
  MEX: 'MXN',
  ZAF: 'ZAR',
  KOR: 'KRW',
  SGP: 'SGD',
  HKG: 'HKD',
  NZL: 'NZD',
  IDN: 'IDR',
  THA: 'THB',
  MYS: 'MYR',
  PHL: 'PHP',
  ISL: 'ISK',
  CZE: 'CZK',
  HUN: 'HUF',
  ROU: 'RON',
  HRV: 'HRK',
  BGD: 'BDT',
  PAK: 'PKR',
  VNM: 'VND',
  EGY: 'EGP',
  NGA: 'NGN',
  ARG: 'ARS',
  CHL: 'CLP',
  COL: 'COP',
  PER: 'PER',
  ISR: 'ILS',
  ARE: 'AED',
  SAU: 'SAR',
  QAT: 'QAR',
  KWT: 'KWD',
  OMN: 'OMR',
  BHR: 'BHD',
  JOR: 'JOD',
  LBN: 'LBP',
  MAR: 'MAD',
  TUN: 'TND',
  DZA: 'DZD',
  LKA: 'LKR',
  NPL: 'NPR',
  KEN: 'KES',
  UGA: 'UGX',
  TZA: 'TZS',
  ETH: 'ETB',
  GHA: 'GHS',
  ZMB: 'ZMW',
  ZWE: 'ZWL',
  MWI: 'MWK',
  MOZ: 'MZN',
  BWA: 'BWP',
  NAM: 'NAD',
  LSO: 'LSL',
  SWZ: 'SZL',
  AGO: 'AOA',
  CMR: 'XAF',
  CIV: 'XOF',
  SEN: 'XOF',
  GIN: 'GNF',
  MLI: 'XOF',
  BFA: 'XOF',
  NER: 'XOF',
  TCD: 'XAF',
  COG: 'XAF',
  GAB: 'XAF',
  GNQ: 'XAF',
  CAF: 'XAF',
  BEN: 'XOF',
  TGO: 'XOF',
  RWA: 'RWF',
  BDI: 'BIF',
  SOM: 'SOS',
  DJI: 'DJF',
  ERI: 'ERN',
  SDN: 'SDG',
  SSD: 'SSP',
  LBR: 'LRD',
  SLE: 'SLL',
  GMB: 'GMD',
  GNB: 'XOF',
  CPV: 'CVE',
  STP: 'STN',
  MUS: 'MUR',
  SYC: 'SCR',
  MDG: 'MGA',
  COM: 'KMF',
  URY: 'UYU',
  PRY: 'PYG',
  BOL: 'BOB',
  VEN: 'VES',
  ECU: 'USD', // Ecuador uses USD
  PAN: 'PAB',
  CRI: 'CRC',
  GTM: 'GTQ',
  HND: 'HNL',
  NIC: 'NIO',
  SLV: 'USD', // El Salvador uses USD
  DOM: 'DOP',
  HTI: 'HTG',
  JAM: 'JMD',
  TTO: 'TTD',
  BHS: 'BSD',
  BRB: 'BBD',
  BLZ: 'BZD',
  GUY: 'GYD',
  SUR: 'SRD',
  ARM: 'AMD',
  AZE: 'AZN',
  GEO: 'GEL',
  KAZ: 'KZT',
  KGZ: 'KGS',
  TJK: 'TJS',
  TKM: 'TMT',
  UZB: 'UZS',
  MNG: 'MNT',
  AFG: 'AFN',
  IRQ: 'IQD',
  IRN: 'IRR',
  YEM: 'YER',
  SYR: 'SYP',
  ALB: 'ALL',
  MKD: 'MKD',
  BIH: 'BAM',
  SRB: 'RSD',
  MNE: 'EUR',
  XKX: 'EUR', // Kosovo
  MDA: 'MDL',
  UKR: 'UAH',
  BLR: 'BYN',
  LAO: 'LAK',
  KHM: 'KHR',
  MMR: 'MMK',
  BTN: 'BTN',
  MDV: 'MVR',
  FJI: 'FJD',
  PNG: 'PGK',
  VUT: 'VUV',
  SLB: 'SBD',
  WSM: 'WST',
  TON: 'TOP',
  KIR: 'AUD', // Kiribati uses AUD
  TUV: 'AUD', // Tuvalu uses AUD
  PLW: 'USD', // Palau uses USD
  FSM: 'USD', // Micronesia uses USD
  MHL: 'USD', // Marshall Islands uses USD
  AND: 'EUR', // Andorra
  LIE: 'CHF', // Liechtenstein
  MCO: 'EUR', // Monaco
  SMR: 'EUR', // San Marino
  VAT: 'EUR', // Vatican City
  BRN: 'BND',
  TLS: 'USD', // Timor-Leste uses USD
  ABW: 'AWG',
  CUW: 'ANG',
  SXM: 'ANG',
  BES: 'USD', // Caribbean Netherlands uses USD
  ATG: 'XCD',
  DMA: 'XCD',
  GRD: 'XCD',
  KNA: 'XCD',
  LCA: 'XCD',
  VCT: 'XCD',
  BMU: 'BMD',
  CYM: 'KYD',
  VGB: 'USD', // British Virgin Islands uses USD
  TCA: 'USD', // Turks and Caicos uses USD
  MSR: 'XCD',
  FLK: 'FKP',
  GIB: 'GIP',
  SHN: 'SHP',
  GRL: 'DKK',
  FRO: 'DKK',
  PRI: 'USD',
  VIR: 'USD',
  GUM: 'USD',
  ASM: 'USD',
  MNP: 'USD',
  NCL: 'XPF',
  PYF: 'XPF',
  WLF: 'XPF',

  // Euro area countries
  AUT: 'EUR', // Austria
  BEL: 'EUR', // Belgium
  CYP: 'EUR', // Cyprus
  EST: 'EUR', // Estonia
  FIN: 'EUR', // Finland
  FRA: 'EUR', // France
  DEU: 'EUR', // Germany
  GRC: 'EUR', // Greece
  IRL: 'EUR', // Ireland
  ITA: 'EUR', // Italy
  LVA: 'EUR', // Latvia
  LTU: 'EUR', // Lithuania
  LUX: 'EUR', // Luxembourg
  MLT: 'EUR', // Malta
  NLD: 'EUR', // Netherlands
  PRT: 'EUR', // Portugal
  SVK: 'EUR', // Slovakia
  SVN: 'EUR', // Slovenia
  ESP: 'EUR', // Spain
}

/**
 * Mapping of currency codes to their full names
 */
export const currencyNames: Record<string, string> = {
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  JPY: 'Japanese Yen',
  CAD: 'Canadian Dollar',
  AUD: 'Australian Dollar',
  CHF: 'Swiss Franc',
  CNY: 'Chinese Yuan',
  INR: 'Indian Rupee',
  NOK: 'Norwegian Krone',
  SEK: 'Swedish Krona',
  DKK: 'Danish Krone',
  PLN: 'Polish Zloty',
  TRY: 'Turkish Lira',
  RUB: 'Russian Ruble',
  BRL: 'Brazilian Real',
  MXN: 'Mexican Peso',
  ZAR: 'South African Rand',
  KRW: 'South Korean Won',
  SGD: 'Singapore Dollar',
  HKD: 'Hong Kong Dollar',
  NZL: 'New Zealand Dollar',
  IDR: 'Indonesian Rupiah',
  THB: 'Thai Baht',
  MYR: 'Malaysian Ringgit',
  PHP: 'Philippine Peso',
  ISK: 'Icelandic Króna',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RON: 'Romanian Leu',
  HRK: 'Croatian Kuna',
  BGD: 'Bangladeshi Taka',
  PKR: 'Pakistani Rupee',
  VND: 'Vietnamese Dong',
  EGP: 'Egyptian Pound',
  NGA: 'Nigerian Naira',
  ARS: 'Argentine Peso',
  CLP: 'Chilean Peso',
  COP: 'Colombian Peso',
  PER: 'Peruvian Sol',
  ILS: 'Israeli Shekel',
  AED: 'UAE Dirham',
  SAR: 'Saudi Riyal',
  QAR: 'Qatari Riyal',
  KWT: 'Kuwaiti Dinar',
  OMR: 'Omani Rial',
  BHD: 'Bahraini Dinar',
  // Add more as needed
}

/**
 * Get flag emoji for country code (ISO 3166-1 alpha-2)
 * Converts alpha-3 to alpha-2 for flag lookup
 */
export function getCountryFlag(countryCode: string): string {
  // Map of common alpha-3 to alpha-2 codes
  const alpha3ToAlpha2: Record<string, string> = {
    USA: 'US',
    GBR: 'GB',
    CAN: 'CA',
    AUS: 'AU',
    DEU: 'DE',
    FRA: 'FR',
    ITA: 'IT',
    ESP: 'ES',
    NLD: 'NL',
    BEL: 'BE',
    AUT: 'AT',
    CHE: 'CH',
    NOR: 'NO',
    SWE: 'SE',
    DNK: 'DK',
    FIN: 'FI',
    POL: 'PL',
    JPN: 'JP',
    CHN: 'CN',
    IND: 'IN',
    RUS: 'RU',
    BRA: 'BR',
    MEX: 'MX',
    ARG: 'AR',
    ZAF: 'ZA',
    EGY: 'EG',
    TUR: 'TR',
    SAU: 'SA',
    ARE: 'AE',
    KOR: 'KR',
    SGP: 'SG',
    HKG: 'HK',
    NZL: 'NZ',
    IDN: 'ID',
    THA: 'TH',
    MYS: 'MY',
    PHL: 'PH',
    VNM: 'VN',
    ISR: 'IL',
    GRC: 'GR',
    PRT: 'PT',
    CZE: 'CZ',
    HUN: 'HU',
    ROU: 'RO',
    BGR: 'BG',
    HRV: 'HR',
    SVK: 'SK',
    SVN: 'SI',
    LTU: 'LT',
    LVA: 'LV',
    EST: 'EE',
    IRL: 'IE',
    ISL: 'IS',
    LUX: 'LU',
    MLT: 'MT',
    CYP: 'CY',
    UKR: 'UA',
    BLR: 'BY',
    KAZ: 'KZ',
    UZB: 'UZ',
    PAK: 'PK',
    BGD: 'BD',
    IRN: 'IR',
    IRQ: 'IQ',
    AFG: 'AF',
    LKA: 'LK',
    NPL: 'NP',
    MMR: 'MM',
    KHM: 'KH',
    LAO: 'LA',
    MNG: 'MN',
    BTN: 'BT',
    MDV: 'MV',
    KEN: 'KE',
    UGA: 'UG',
    TZA: 'TZ',
    ETH: 'ET',
    GHA: 'GH',
    NGA: 'NG',
    ZMB: 'ZM',
    ZWE: 'ZW',
    BWA: 'BW',
    NAM: 'NA',
    AGO: 'AO',
    MOZ: 'MZ',
    MWI: 'MW',
    MDG: 'MG',
    RWA: 'RW',
    BDI: 'BI',
    SOM: 'SO',
    DJI: 'DJ',
    ERI: 'ER',
    SDN: 'SD',
    SSD: 'SS',
    CMR: 'CM',
    CIV: 'CI',
    SEN: 'SN',
    GIN: 'GN',
    MLI: 'ML',
    BFA: 'BF',
    NER: 'NE',
    TCD: 'TD',
    COG: 'CG',
    GAB: 'GA',
    GNQ: 'GQ',
    CAF: 'CF',
    BEN: 'BJ',
    TGO: 'TG',
    LBR: 'LR',
    SLE: 'SL',
    GMB: 'GM',
    GNB: 'GW',
    CPV: 'CV',
    STP: 'ST',
    MUS: 'MU',
    SYC: 'SC',
    COM: 'KM',
    CHL: 'CL',
    URY: 'UY',
    PRY: 'PY',
    BOL: 'BO',
    VEN: 'VE',
    ECU: 'EC',
    COL: 'CO',
    PER: 'PE',
    PAN: 'PA',
    CRI: 'CR',
    GTM: 'GT',
    HND: 'HN',
    NIC: 'NI',
    SLV: 'SV',
    DOM: 'DO',
    HTI: 'HT',
    JAM: 'JM',
    TTO: 'TT',
    BHS: 'BS',
    BRB: 'BB',
    BLZ: 'BZ',
    GUY: 'GY',
    SUR: 'SR',
    ARM: 'AM',
    AZE: 'AZ',
    GEO: 'GE',
    KGZ: 'KG',
    TJK: 'TJ',
    TKM: 'TM',
    ALB: 'AL',
    MKD: 'MK',
    BIH: 'BA',
    SRB: 'RS',
    MNE: 'ME',
    XKX: 'XK',
    MDA: 'MD',
    YEM: 'YE',
    SYR: 'SY',
    JOR: 'JO',
    LBN: 'LB',
    KWT: 'KW',
    QAT: 'QA',
    BHR: 'BH',
    OMN: 'OM',
    MAR: 'MA',
    TUN: 'TN',
    DZA: 'DZ',
    LBY: 'LY',
    FJI: 'FJ',
    PNG: 'PG',
    VUT: 'VU',
    SLB: 'SB',
    WSM: 'WS',
    TON: 'TO',
    KIR: 'KI',
    TUV: 'TV',
    PLW: 'PW',
    FSM: 'FM',
    MHL: 'MH',
    AND: 'AD',
    LIE: 'LI',
    MCO: 'MC',
    SMR: 'SM',
    VAT: 'VA',
    BRN: 'BN',
    TLS: 'TL',
    ABW: 'AW',
    CUW: 'CW',
    SXM: 'SX',
    ATG: 'AG',
    DMA: 'DM',
    GRD: 'GD',
    KNA: 'KN',
    LCA: 'LC',
    VCT: 'VC',
    BMU: 'BM',
    CYM: 'KY',
    VGB: 'VG',
    TCA: 'TC',
    MSR: 'MS',
    FLK: 'FK',
    GIB: 'GI',
    SHN: 'SH',
    GRL: 'GL',
    FRO: 'FO',
    PRI: 'PR',
    VIR: 'VI',
    GUM: 'GU',
    ASM: 'AS',
    MNP: 'MP',
    NCL: 'NC',
    PYF: 'PF',
    WLF: 'WF',
    LSO: 'LS',
    SWZ: 'SZ',
  }

  const alpha2 = alpha3ToAlpha2[countryCode]
  if (!alpha2) {
    return '🌍' // Default globe emoji if country not found
  }

  // Convert alpha-2 to flag emoji using regional indicator symbols
  const codePoints = [...alpha2].map((char) => 127397 + char.charCodeAt(0))
  return String.fromCodePoint(...codePoints)
}

/**
 * Get currency code to country code mapping (reverse)
 * For currencies used by multiple countries, use the most representative one
 */
export function getCurrencyToCountryCode(): Record<string, string> {
  const reverseMap: Record<string, string> = {
    // Explicitly set EUR to use Germany as the representative
    EUR: 'DEU',
    // USD is used by many countries, use USA
    USD: 'USA',
    // XOF (West African CFA franc) - use Senegal
    XOF: 'SEN',
    // XAF (Central African CFA franc) - use Cameroon
    XAF: 'CMR',
    // XCD (East Caribbean dollar) - use Antigua
    XCD: 'ATG',
    // XPF (CFP franc) - use French Polynesia
    XPF: 'PYF',
  }

  for (const [countryCode, currencyCode] of Object.entries(countryCodeToCurrencyCode)) {
    // Use the first country for each currency (unless already set)
    if (!reverseMap[currencyCode]) {
      reverseMap[currencyCode] = countryCode
    }
  }

  return reverseMap
}
